Adding support to install features and fixes
paketo-buildpacks/liberty pull request #102
Opened 2022-03-15 20:06 UTC by kevin-ortega

## Summary

Add support to install Liberty features and Liberty fixes.
## Use Cases

Most liberty profiles have a subset of all available features.   This PR will give the user a method to install liberty features they want to use with a smaller footprint profile.   Features are specified in a space delimited list in the environment variable `BP_LIBERTY_FEATURES`.

iFixes are interim fixes that can be applied to a liberty installation  Typically, these are security or vulnerability fixes that require immediate remediation and can not wait until the next Liberty release.   This PR provides a method to install iFixes using an external configuration package.   

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-03-16 13:21 UTC, dmikusa-pivotal requested changes
We need to have some unit tests for a.) installing features and b.) installing ifixes.

2022-03-16 13:21 UTC, dmikusa-pivotal commented on liberty/base.go
> +	profile, _ := b.ConfigurationResolver.Resolve("BP_LIBERTY_PROFILE")
Same comment about the path as above. We should pass in the path instead of trying to construct it.

2022-03-16 13:21 UTC, dmikusa-pivotal commented on liberty/base.go
> +		executor := effect.NewExecutor()
Same comment above about the executor. Pass one in so it can be mocked/tested.

2022-03-16 13:21 UTC, dmikusa-pivotal commented on liberty/base.go
> +	fixes, error := ioutil.ReadDir(filepath.Join(confPath, "ifixes"))
```suggestion
	fixes, err := ioutil.ReadDir(filepath.Join(confPath, "ifixes"))
```

Using `err` for the name of the returned err is convention.

2022-03-16 13:21 UTC, dmikusa-pivotal commented on liberty/base.go
> +	}
This needs to be move up above right after the call to `ReadDir`. The error check has to happen first thing after a method call or it can get really confusing as to what triggered an error (and you can potentially miss handling an error).

This typically gets handled in three parts in Go. 1.) handle major errors 2.) handle our target directory doesn't exist (also an error, but we don't want to treat it as one) 3.) handle success case.

```
fixes, err := ioutil.ReadDir(filepath.Join(confPath, "ifixes"))
if err != nil && !os.IsNotExist(err) {
    return fmt.Errorf("unable to read ifixes directory\n%w", err)
} else if os.IsNotExist(err) {
    b.Logger.Debug("no ifixes present, skipping")
} else {
    // parse & handle ifixes
}
```

2022-03-16 19:13 UTC, kevin-ortega commented on liberty/base.go
> +		features := strings.Fields(listoffeatures)
Thanks an excellent point.  It certainly is possible a custom feature could depend on a standard feature.  I will switch the order.

2022-03-17 16:00 UTC, kevin-ortega commented on liberty/base.go
> +		installationLocation := fmt.Sprintf("/layers/paketo-buildpacks_liberty/open-liberty-runtime-%s", profile)
@dmikusa-pivotal I'm struggling figuring out how to get the installation location in build to pass to base.   Any sample I can look at?

2022-03-24 15:21 UTC, dmikusa-pivotal commented
Closing in favor of https://github.com/paketo-buildpacks/liberty/pull/123/

2022-03-24 15:21 UTC, closed without merging