Provide server config during build
paketo-buildpacks/liberty pull request #154
Opened 2022-04-19 18:51 UTC by hibell

## Summary
Fixes #66. Allow users to provide server config during build.

## Use Cases

Users that want to provide Liberty config during build are now able to. At the moment, this requires one of the env vars to be set during the build:

### Maven

```
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*"
```

### Gradle

```
--env BP_GRADLE_BUILT_ARTIFACT="build/libs/*.[ejw]ar src/main/liberty/config/*"
```

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-04-27 15:31 UTC, dmikusa-pivotal requested changes

2022-04-27 15:31 UTC, dmikusa-pivotal commented on helper/linker.go
> +	_ = os.Remove(linkPath) // we don't care if this succeeds or fails necessarily, we just want to try to remove anything in the way of the relinking
You might want to take the error and check that it's not a "no file exists" error. I can see skipping that error, but there could potentially be other errors that would be ignored here. Like let's say the filesystem is read-only for some reason, the remove would fail and we'd ignore that.

Go has `os.IsNotExist(err error)` so you can test the error to see if it's complaining cause the file does not exist, then ignore that case, but still handle other failures.

2022-04-27 15:31 UTC, dmikusa-pivotal commented on helper/linker.go
> +func (f FileLinker) ContributeApp(workspacePath string, config ServerConfig, binding libcnb.Binding) error {
I'm not following the logic change in this method. It seems unrelated to the problem. Especially, the part around expanding the app file. Or is there a need to expand the file so that the config file is accessible?

Just trying to understand if this change is related to the issue or another improvement we're bundling together. Either is OK, just making sure I follow along.

2022-04-27 15:31 UTC, dmikusa-pivotal commented on helper/linker.go
> +			toPath := filepath.Join(f.ServerRootPath, config)
I think the way you'd typically handle this in Go is to just try the file operation, so just run `util.DeleteAndLinkPath(..)` but then check the return `err` to see if it matches a file not found error (see `os.IsNotExist(err error)`. If it's file not found, you ignore the error and move on.

Doing it this way avoids potential race conditions between checking if the file exists and actually performing the file operation. I'm not sure that race conditions matters a ton here, but I do think doing it this way would be more idiomatic Go code.

2022-05-05 13:55 UTC, hibell commented on helper/linker.go
> +func (f FileLinker) ContributeApp(workspacePath string, config ServerConfig, binding libcnb.Binding) error {
@dmikusa-pivotal The changes are relevant to the problem. The linker needs to determine if `/workspace` has any `*.ear` or `*.war` files or if `/workspace` is the app itself:

* If a compiled artifact was found, expand it into `<server-dir>/apps/app`
* If no apps were found, assume `/workspace` is the app itself and link it to `<server-dir>/apps/app` (current behavior)

I expanded the app to match the current behavior if Maven/Gradle builds the app. Also the Liberty runtime will look for the app at `<server-dir>/apps/app` so it made sense to just make that directory and expand the compiled artifact into it. Let me know if you have ideas on improving this.

2022-05-11 14:01 UTC, dmikusa-pivotal commented on README.md
> +At the moment, these files can only be included in the build by telling the Maven or Gradle buildpacks to provide them.
```suggestion
At the moment, these files can only be included in the build by telling the Maven or Gradle buildpacks to provide them. Thus this method of including server configuration can only be performed when building from source code, it will not work when building with a pre-compiled WAR file.

```

2022-05-11 15:39 UTC, merged