Move linker logic into build
paketo-buildpacks/liberty pull request #200
Opened 2022-07-18 14:31 UTC by hibell

These changes are necessary to be compliant with stricter security
settings where build and run user ID will be different.

Fixes #70, #156, #197 

## Summary
This change gets rid of the linker as it won't be usable with the stricter security settings coming to buildpacks. I included changes for issue 156 to include a proper default server.xml as it is necessary during the build process now (e.g. for installing server features).

## Use Cases
Necessary for stricter security settings coming to buildpacks.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-07-21 18:50 UTC, dmikusa-pivotal requested changes
I didn't look through the whole PR, but noticed a few things.

I also am wondering about the removal of the helper. I think that's going to cause problems, see my other comment, but from a high level I was curious why you removed that? Is it causing problems with something? Thanks

2022-07-21 18:50 UTC, dmikusa-pivotal commented on README.md
> +* If a web application was built, it will be symlink `<APPLICATION_ROOT>` to `<WLP_USR_DIR>/servers/<SERVER_NAME>/apps/app`
```suggestion
* If a web application was built, it will symlink `<APPLICATION_ROOT>` to `<WLP_USR_DIR>/servers/<SERVER_NAME>/apps/app`
```

2022-07-21 18:50 UTC, dmikusa-pivotal commented on scripts/build.sh
> -
This shouldn't be deleted. We still need the block. If removing helper, just remove the `bin/helper` part on line 9.

2022-07-21 18:50 UTC, dmikusa-pivotal commented on liberty/base.go
> +	}
I wonder if this functionality is still necessary? It's a non-trivial amount of code to retain to implement it and there are a number of other ways to influence the server configuration, including specifying a server bundle which is the complete set of configuration.

What do you think @hibell ?

2022-07-21 18:50 UTC, dmikusa-pivotal commented on liberty/base.go
> +	}
You should not need to do this. The BuildContext has that information already, `context.Platform.Bindings`. You probably just need to pass it into the contributor from build.

2022-07-21 18:50 UTC, dmikusa-pivotal commented on liberty/base.go
> +				return fmt.Errorf("unable to replace server.xml\n%w", err)
By moving the evaluation of bindings into the build from the exec.d helper (which runs at runtime), there are a couple of notable changes:

1. The output of this action is saved into the image. Since we are copying server.xml and bootstrap.properties from the secret at build time, that will end up with those files in the generated image. Image storage is not secure and anyone can open an image and look at the contents. That is often viewed as a security/information leak. Given that, I would strongly not recommend moving this functionality to build time. A binding is secret by design, so we have to treat it that way.

2. You lose some flexibility. Since this code is processing the bindings at build time, that means you need to rebuild to change those configuration files. If they are processed at runtime, it's more flexible and you don't need to rebuild the image to change the file.

I think 2.) is nice to have, but 1.) is probably a requirement. We need to either process that at runtime or change from using bindings/secrets to something else.

2022-08-01 21:43 UTC, hibell commented on liberty/base.go
> +	}
Agreed. Custom features were supplied via the external configuration dependency. They can now be supplied by mounting a volume containing the features to `/features` similar to how we handle fixes.

2022-08-01 21:45 UTC, hibell commented on liberty/base.go
> +				return fmt.Errorf("unable to replace server.xml\n%w", err)
I restored the exec.d helper which now only evaluates the bindings.

2022-08-15 14:26 UTC, hibell commented
@dmikusa-pivotal Hey Daniel. Are you able to review this PR soon? We have an internal user waiting for these changes. Thanks.

2022-08-15 20:45 UTC, dmikusa-pivotal commented
Apologizes, I missed your force push and didn't realize this needed a review. I'll try to take a look Tue or Wed at the latest.

2022-08-19 01:48 UTC, dmikusa-pivotal commented
A couple of notes:

1. There's a *lot* going on here. In the future, it would be easier to review & merge PRs that are smaller. One change per PR is a good mantra to follow.
2. I like how this is simplifying things, seems like we're deleting a lot of code which I always like :) There is definitely some breaking changes in this though, like removing support for external configuration. I'm OK with this, but I'm changing the label to "semver:major", so we cut a new major release for this. I would also ask that you help with a few release note highlight so we cover all the changes well in the release notes. I'll ping you on Slack about this.
3. There's a lot going on with the "using a liberty stack" docs. I don't really have the capacity to test that and I'm not familiar with the images & things being done there. @kevin-ortega would you be able to double-check that so we can get a second set of eyes on it. If it looks good to you, give me a 👍 and I can merge this.

Thanks!

2022-08-19 01:49 UTC, dmikusa-pivotal approved these changes

2022-08-19 16:05 UTC, kevin-ortega commented
> 3. There's a lot going on with the "using a liberty stack" docs. I don't really have the capacity to test that and I'm not familiar with the images & things being done there. @kevin-ortega would you be able to double-check that so we can get a second set of eyes on it. If it looks good to you, give me a 👍 and I can merge this.
> 
> Thanks!

I have reviewed this doc and verified it is accurate.

2022-08-19 16:41 UTC, merged