Build server and app shared class cache
paketo-buildpacks/liberty pull request #379
Opened 2023-02-14 14:53 UTC by hibell

## Summary
This change builds a shared class cache (SCC) for Liberty during the build to improve app startup times. The following build config options were added:

* `BP_LIBERTY_SCC_DISABLED` disables the SCC from being built (default: false)
* `BP_LIBERTY_SCC_SIZE_MB` controls the size of the initial SCC (default: 100mb)
* `BP_LIBERTY_SCC_NUM_ITERATIONS` controls the number of times the server is started/stopped when building the SCC
* `BP_LIBERTY_SCC_TRIM_SIZE_DISABLED` controls whether the SCC's size is trimmed in the end.

## Use Cases

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2023-03-06 04:30 UTC, dmikusa requested changes
This generally looks good to me. A couple of thoughts (other comments) and one suggestion (below).

I know that you log info about the size of the cache when you create/resize it. It might also be interesting to log the final size of the cache that is added to the image. What's being logged now, to me, reads like you might have up to that amount of data in the cache, but if you walked the tree of the cache directory and calculated the actual size of what is being added I could see that being useful to users. You then know that with this feature enabled, my images are exactly X MB larger. Just a thought, not a requirement.

2023-03-06 04:30 UTC, dmikusa commented on internal/util/jvm.go
> +		return "", fmt.Errorf("unable to read cache ratio\n%w", err)
```suggestion
		return "", fmt.Errorf("unable to read JVM name\n%w", err)
```

2023-03-06 04:30 UTC, dmikusa commented on internal/util/jvm.go
> +	}
```suggestion
	r := regexp.MustCompile(`Cache is (\d+)% full`)
```

You can probably use MustCompile here. The regular expression is a static string, so if it works in testing it should never panic. 

https://pkg.go.dev/regexp#MustCompile

2023-03-06 04:30 UTC, dmikusa commented on internal/util/jvm.go
> +				return 0.0, err
```suggestion
				return 0.0, fmt.Errorf("unable to parse [%s] to int\n%w", matches[1], err)
```

I'm not sure everyone in Go-land would agree with me, but I will always wrap errors. I find it easier to debug things because it creates a basic stack trace, which I miss in Go.

2023-03-08 14:30 UTC, hibell commented
Thanks for the review.

> I know that you log info about the size of the cache when you create/resize it. It might also be interesting to log the final size of the cache that is added to the image. What's being logged now, to me, reads like you might have up to that amount of data in the cache, but if you walked the tree of the cache directory and calculated the actual size of what is being added I could see that being useful to users. You then know that with this feature enabled, my images are exactly X MB larger. Just a thought, not a requirement.

The cache uses a single binary file per cache layer created so we should only have 1 file for our cache. The build reports that the final cache size is:

```text
Cache is 56% full
    Resizing cache from 100m to 56m
```

and when we take a look at the file information and size, we see 56MB for the cache file:

```shell
$ file /tmp/C290M11F1A64P_liberty_G43L00
/tmp/C290M11F1A64P_liberty_G43L00: data

$ ls -hal /layers/paketo-buildpacks_liberty/open-liberty-runtime-full/output/.classCache/C290M11F1A64P_liberty_G43L00
-rw-rw-r-- 1 cnb cnb 56M Jan  1  1980 /layers/paketo-buildpacks_liberty/open-liberty-runtime-full/output/.classCache/C290M11F1A64P_liberty_G43L00
```

The delta in image file sizes are approximately equivalent the cache size:
* Sample app with cache: 646MB
* Sample app without cache: 585MB
* Delta: 61MB

2023-03-08 15:38 UTC, kevin-ortega approved these changes
LGTM

2023-03-08 16:24 UTC, dmikusa approved these changes

2023-03-08 16:24 UTC, merged